# Generated by Django 2.1 on 2018-09-09 22:01

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='createuser',
            managers=[
                ('objects', students.models.StudentManager()),
            ],
        ),
        migrations.AddField(
            model_name='createuser',
            name='last_login',
            field=models.DateField(auto_now=True),
        ),
    ]
